spring:
  graphql:
    cors:
      allowed-headers: '*'
    path: "/graphql-spring"
  threads:
    virtual:
      enabled: false

graphql:
  servlet:
    async:
      enabled: true
    enabled: true
    corsEnabled: true
    cors:
      allowed-origins: '*'
    exception-handlers-enabled: true # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
    actuator-metrics: true
    tracing-enabled: false

  tools:
    schema-location-pattern: '**/*.graphqls'
  playground:
    enabled: true
