spring:
  graphql:
    cors:
      allowed-headers: '*'
    path: "/graphql-spring"
  threads:
    virtual:
      enabled: false

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces



logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false

graphql:
  servlet:
    async:
      enabled: true
    enabled: true
    corsEnabled: true
    cors:
      allowed-origins: '*'
    exception-handlers-enabled: true # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
    actuator-metrics: true
    tracing-enabled: false

  tools:
    schema-location-pattern: '**/*.graphqls'
  playground:
    enabled: true
