global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'spring boot scrape'
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9251',
                   'host.docker.internal:9252',
                   'host.docker.internal:9253',
                   'host.docker.internal:9254',
                   'host.docker.internal:9255',
                   'host.docker.internal:9256',
                   'host.docker.internal:9258'
      ]
  - job_name: "zookeeper"
    static_configs:
      - targets:
          - "zookeeper:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'


  - job_name: "kafka-broker"
    static_configs:
      - targets:
          - "kafka:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'


  - job_name: "schema-registry"
    static_configs:
      - targets:
          - "schema-registry:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'